sudo: true
language: php
dist: trusty

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can unintended consequences including a
# non-functional prod environment.
php:
  - 7.2

install:
 - sudo pip install -U pytablewriter termcolor

script:
  - echo "$DIST"
  - lsb_release -a
  - python ./test.py
