sudo: true
language: php
dist: trusty

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can unintended consequences including a
# non-functional prod environment.
php:
  - 7.2

install:
 - sudo apt-get update
 - sudo apt-get install python3-pip
 - sudo pip3 install -U pytablewriter termcolor

script:
  - echo "$DIST"
  - lsb_release -a
  - python3 ./test.py
