language: python

python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- 'pypy'

install: pip install -r requirements.txt

script: python ./test.py

matrix:
  allow_failures:
    - python: 'pypy'

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py       | tee >(wc -l)
  - pyflakes *.py   | tee >(wc -l)
