language: python

dist: xenial

#arch:
#  - amd64  # Default
#  - arm64  # No Python images yet on xenial

matrix:
  fast_finish: true
  include:
    - python:  'pypy3'
    - python:  '3.9'
    - python:  '3.9'
      dist:  bionic
    - python:  '3.9'
      dist:  focal
    - python:  '3.8'
    - python:  '3.7'
    - python:  '3.6'
    - python:  '3.5'
    - python:  'nightly'
    - python:  '3.10-dev'
    - python:  '3.9-dev'
    - python:  '3.8-dev'
    - python:  '3.7-dev'
    - python:  '3.6-dev'

install:
 - pip install -U pytest tqdm
 - pip install -U pytest black

script:
  - echo "$TRAVIS_EVENT_TYPE"
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py
  - pytest
  - python -m pytest -v -x -W always
  - black . --check --diff
