language: python

python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- 'pypy'

install:

  - time CFLAGS=-O0 pip install diff_cover

#  - time pip install pep8
#  - time pip install pyflakes
#  - time pip install diff_cover

script: python ./test.py

matrix:
  allow_failures:
    - python: 'pypy'

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py       | tee >(wc -l)
  - pyflakes *.py   | tee >(wc -l)
