language: python

dist: xenial

matrix:
  include:
    - python: 'pypy'
    - python: 'pypy3'
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'
    - python: '2.7'
    - python: 'nightly'
    - python: '3.8-dev'

install:
 - pip install -U pytest

script:
  - echo "$DIST"
  - lsb_release -a

  - pytest --version
  - pytest -rs test.py
