language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: '3.6'
    - python: '2.7'
    - env: DOCKER="alpine" DOCKER_TAG="pytest"
    - env: DOCKER="arch" DOCKER_TAG="pytest"

dist: trusty

sudo: required

install:
  - if [ "$DOCKER" == "" ]; then echo "do non-docker install.sh"; fi

before_install:
  - if [ "$DOCKER" ]; then echo "do docker pull"; fi

before_script:
  - echo "do before_script setup"

script:
  - |
       if [ "$DOCKER" == "" ]; then
          echo "do non-docker script.sh"
       else
          echo "do docker run"
       fi

after_success:
  - echo "do after_success.sh"

env:
  global:
    secure: "etc"
