language: python

dist: xenial

services:
  - xvfb

# These env vars have no effect other than to show it in the env vars column
matrix:
  include:
    - python: '3.7'
      env:  xenial
    - python: '3.6'
      env:  xenial
    - python: '3.6'
      env:  trusty
      dist: trusty
      sudo: false
    - python: '3.5'
      env:  xenial
    - python: '3.5'
      env:  trusty
      dist: trusty
      sudo: false
    - python: '3.4'
      env:  trusty
      dist: trusty
      sudo: false
    - python: '2.7'
      env:  xenial
    - python: '2.7'
      env:  trusty
      dist: trusty
      sudo: false
    - python: 'pypy'
      env:  trusty
      dist: trusty
      sudo: false
    - python: 'pypy3'
      env:  trusty
      dist: trusty
      sudo: false
    - python: 'nightly'
      env:  xenial
    - python: 'nightly'
      env:  trusty
      dist: trusty
      sudo: false
    - python: '3.7-dev'
      env:  xenial
    - python: '3.7-dev'
      env:  trusty
      dist: trusty
      sudo: false
    - python: '3.6-dev'
      env:  xenial
    - python: '3.6-dev'
      env:  trusty
      dist: trusty
      sudo: false

script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
