language: python

dist: xenial

# These env vars have no effect other than to show it in the env vars column
matrix:
  include:
    - python: 'pypy2.7-7.0'
      env:  xenial
      dist: xenial
    - python: 'pypy3.5-7.0'
      env:  xenial
      dist: xenial
    - python: 'pypy2.7-6.0'
      env:  xenial
      dist: xenial
    - python: 'pypy3.5-6.0'
      env:  xenial
      dist: xenial
    - python: 'pypy'
      env:  trusty
      dist: trusty
    - python: 'pypy3'
      env:  trusty
      dist: trusty
    - python: '3.7'
      env:  xenial
    - python: '3.6'
      env:  xenial
    - python: '3.6'
      env:  trusty
      dist: trusty
    - python: '3.5'
      env:  xenial
    - python: '3.5'
      env:  trusty
      dist: trusty
    - python: '2.7'
      env:  xenial
    - python: '2.7'
      env:  trusty
      dist: trusty
    - python: 'nightly'
      env:  xenial
    - python: 'nightly'
      env:  trusty
      dist: trusty
    - python: '3.7-dev'
      env:  xenial
    - python: '3.7-dev'
      env:  trusty
      dist: trusty
    - python: '3.6-dev'
      env:  xenial
    - python: '3.6-dev'
      env:  trusty
      dist: trusty

install:
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python ./test.py

