language: python

python:
- 'pypy'
- 'pypy3'
- '3.2'
- '3.3'
- '3.4'
- '2.6'
- '2.7'

sudo: false

install:
  - "echo $TRAVIS_PYTHON_VERSION"

  # Fetch the remote master branch before running diff-cover on Travis CI.
  # https://github.com/edx/diff-cover#troubleshooting
  - git fetch origin master:refs/remotes/origin/master

  # CFLAGS=-O0 means build with no optimisation.
  # Makes build much quicker for lxml and other dependencies.
  - time CFLAGS=-O0 pip install --use-wheel diff_cover

script:
  - python ./test.py
