language: python

python:
- 'pypy'
- 'pypy3'
- 'pypy3-5.9.0'
- 'pypy3-5.9'
- 'pypy-5.9.0'
- 'pypy-5.9'
- 'pypy3-5.9.0'
- 'pypy3-5.9'
- 'pypy-5.9.0'
- 'pypy-5.9'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.6.3'
- '3.6-dev'
- '3.7-dev'
- 'nightly'
- '2.6'
- '2.7'

cache: pip

dist: trusty

# Use container-based infrastructure
sudo: false

install:
 - pip install -U pip
 - pip install pillow

script:
  - python ./test.py

