language: python

dist: bionic

# These env vars have no effect other than to show it in the env vars column
matrix:
  include:
    - python: 'pypy'
    - python: 'pypy3'
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'
    - python: '2.7'
    - python: 'nightly'
    - python: '3.8-dev'

install:
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python ./test.py

