language: python

python:
- '3.2'
- '3.3'
- '3.4'
- 'pypy3'
- '2.6'
- '2.7'
- 'pypy'

sudo: false

install:
  - time pip install --upgrade pip
  - time pip install docutils
#  - pip install git+git://github.com/hugovk/docutils.git@parallel-2to3
  - "echo $TRAVIS_PYTHON_VERSION"

script:
  - python ./test.py
