language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

cache: pip

sudo: false
addons:
  apt_packages:
  - git
  - curl
  - nginx

install:
  - CFLAGS="-O0" pip install lxml
  - "echo $TRAVIS_PYTHON_VERSION"
  - "echo $TRAVIS_BRANCH"
  - "echo $USER"
  - "echo $TRAVIS_REPO_SLUG"
  - |
     if [ "$TRAVIS_REPO_SLUG" = "hugovk/test" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "do something..."
     fi

script:
  - python ./test.py
