language: python

python:
- 'nightly'
- '3.7-dev'
- '3.7.0b3'
- '3.7'
- '3.6-dev'
- '3.6'
- '3.5'
- '3.4'
- '3.3'
- '2.7'
- '2.6'
- 'pypy'
- 'pypy3'

cache: pip

dist: trusty

# Use container-based infrastructure
sudo: false

install:
 - pip install -U pip
 - pip install Cython
 - pip install pillow

script:
  - python ./test.py

