language: python

python:
- '3.7-dev'
- '3.6'
- '3.5'
- '3.4'
- '3.3'
- '2.7'
- '2.6'
- 'pypy'
- 'pypy3'
- 'nightly'
- '3.7-dev'
- '3.6-dev'

# Use container-based infrastructure
sudo: false

install:
 - pip install -U pip setuptools wheel
 - pip install -U pillow

script:
  - python ./test.py

