language: python

dist: xenial

arch:
  - amd64  # Default
  - arm64
  - ppc64le
  - s390x

python:
  - 'pypy3'
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'

install:
 - pip install -U pip
 - pip install -U pillow

script:
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py
