language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'

# Use container-based infrastructure
sudo: false

install:
 # pip 8.0.0 doesn't support Python 3.2
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install -U "pip<8.0.0"; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install -U pip; fi

 - "pip install pillow"

script:
  - python ./test.py
