language: php

services:
- mysql
- docker

php:
  - 7.3

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR
    - SIMPLETEST_DB=mysql://drupal:drupal@localhost/drupal
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8888
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - SERVICE_NAME=$(basename $TRAVIS_REPO_SLUG)
    - NGINX_DOCKER_IMAGE=$SERVICE_NAME-nginx:$VERSION_NUMBER
    - PHP_DOCKER_IMAGE=$SERVICE_NAME:$VERSION_NUMBER
    - PATH=~/bin:$PATH
  matrix:
    - MY_VAR=abc  MY_OTHER_VAR=123
    - MY_VAR=abc  MY_OTHER_VAR=789
    - MY_VAR=xyz  MY_OTHER_VAR=123
    - MY_VAR=xyz  MY_OTHER_VAR=789

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  pip: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - ".rules"

addons:
  ssh_known_hosts:
  # - svn-4786.devcloud.hosting.acquia.com
  chrome: stable

before_install:
  - echo "Primary tests"
  - echo before_install
  - echo before_install
  - echo before_install
  - echo before_install
  - echo before_install
  - echo before_install

stage: "Test"
name: "Primary tests"
install:
  - echo "Primary tests"
  - echo install
  - echo install
  - echo install

script:
  - echo "Primary tests"
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script
  - echo script

after_success:
  - echo "Primary tests"
  - echo after_success
  - echo after_success
  - echo after_success
  - echo after_success
  - echo after_success
  - echo after_success
  - echo after_success
  - echo after_success
  - echo after_success
