language: python

dist: xenial

arch:
  - amd64
  - arm64

python:
  - 'pypy'
  - 'pypy3'
  - 'pypy2.7-7.0'
  - 'pypy3-7'
  - 'pypy3-7.0'
  - 'pypy3-7.1'
  - 'pypy3.5-7.0'
  - 'pypy3.6-7'
  - 'pypy3.6-7.0'
  - 'pypy3.6-7.1'
  - 'pypy2.7-6.0'
  - 'pypy3.5-6.0'
  - '3.7'
  - '3.6'
  - '3.5'
  - '2.7'
  - 'nightly'
  - '3.7-dev'
  - '3.8-dev'
  - '3.6-dev'

install:
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py

