language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'

install:
  - time pip install pillow

script: python ./test.py

matrix:
  allow_failures:
    - python: 'pypy'

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py       | tee >(wc -l)
  - pyflakes *.py   | tee >(wc -l)
