language: python

python:
- '3.7-dev'
- '3.6'
- '3.5'
- '3.4'
- '2.7'
- 'pypy'
- 'pypy3'
- 'nightly'
- '3.7-dev'
- '3.6-dev'

# Use container-based infrastructure
sudo: false

install:
 - pip install -U scipy

script:
  - python ./test.py

