language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'

install:
  - "echo $TRAVIS_PYTHON_VERSION"
  - "echo $TRAVIS_BRANCH"
  - "echo $USER"

script:
  - python ./test.py
