language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'

# Use container-based infrastructure
sudo: false

install:
  - "pip install pillow"

script:
  - python ./test.py
