language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'

install:
  - "echo $TRAVIS_PYTHON_VERSION"
  - "echo $TRAVIS_BRANCH"
  - "echo $USER"
  - "echo $TRAVIS_REPO_SLUG"
  - |
     if [ "$TRAVIS_REPO_SLUG" = "hugovk/test" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "do something..."
     fi

script:
  - python ./test.py
  - grep --silent tinylittleneedle test.py # shouldn't be found, hopefully will return 0 and no error
