language: python

# These env vars have no effect other than to show it in the env vars column
matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: required
    - python: '2.7'

install:
 - pip install -U pytablewriter termcolor

script:
  - echo "$DIST"
  - lsb_release -a
  - python ./test.py
