language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'

sudo: false

install:
  - time pip install --upgrade pip
#  - time pip install docutils
  - pip install git+git://github.com/docutils-mirror/docutils.git
  - "echo $TRAVIS_PYTHON_VERSION"

script:
  - python ./test.py
