language: python
env:
  matrix:
  - TOXENV=lint
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
sudo: false
install:
- travis_retry pip install tox
- travis_retry pip install coveralls
script: tox
matrix:
  allow_failures:
  - python: '3.4'
  - python: pypy
  - python: pypy3
  fast_finish: true
