language: python

dist: xenial

# These env vars have no effect other than to show it in the env vars column
matrix:
  include:
    - python: 'pypy'
    - python: 'pypy3'
    - python: 'pypy2.7-7.0'
    - python: 'pypy3-7'
    - python: 'pypy3-7.0'
    - python: 'pypy3-7.1'
    - python: 'pypy3.5-7.0'
    - python: 'pypy3.6-7'
    - python: 'pypy3.6-7.0'
    - python: 'pypy3.6-7.1'
    - python: 'pypy2.7-6.0'
    - python: 'pypy3.5-6.0'
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'
    - python: '2.7'
    - python: 'nightly'
    - python: '3.7-dev'
    - python: '3.8-dev'
    - python: '3.6-dev'

install:
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py

