language: python

dist: xenial

#arch:
#  - amd64  # Default
#  - arm64  # No Python images yet on xenial

python:
  - 'pypy3'
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - 'nightly'
  - '3.10-dev'
  - '3.9-dev'
  - '3.8-dev'
  - '3.7-dev'
  - '3.6-dev'

install:
 - pip install -U pip
 - pip install -U travis-tox

script:
  - echo "$TRAVIS_EVENT_TYPE"
  - echo "$DIST"
  - lsb_release -a
  - python --version
