language: python

sudo: false

python:
- 'pypy'
- 'pypy3'
- 'pypy-5.3.1'
- 'pypy-5.4'
- 'pypy-5.4.1'
- 'pypy-5.6'
- 'pypy-5.6.0'
- '2.6'
- '2.7'
- '2.7.12'
- '3.2'
- '3.2.6'
- '3.3'
- '3.3.6'
- '3.4'
- '3.4.5'
- '3.5'
- "3.5-dev" # 3.5 development branch
- "3.6-dev" # 3.6 development branch
- "nightly" # currently points to 3.7-dev

install:
  - "echo $TRAVIS_PYTHON_VERSION"
  - pip install pyyaml

script:
  - python ./test.py
