language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'

sudo: false
addons:
  apt_packages:
  - git
  - curl
  - nginx

install:
  - "echo $TRAVIS_PYTHON_VERSION"
  - "echo $TRAVIS_BRANCH"
  - "echo $USER"
  - "echo $TRAVIS_REPO_SLUG"
  - |
     if [ "$TRAVIS_REPO_SLUG" = "hugovk/test" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "do something..."
     fi

script:
  - python ./test.py

after_script:
  - echo "Clones detected" | grep -E "Clones detected\|lines are duplicates"
  - echo "Clones detected" | grep -E "Clones detected|lines are duplicates"
  - echo "Clones detected" | grep -e "Clones detected\|lines are duplicates"
  - echo "Clones detected" | grep -e "Clones detected|lines are duplicates"
