language: python

dist: xenial

python:
  - '3.8'
  - '3.7'
  - '3.6'

install:
 - pip install -U flit
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py
