language: python

dist: xenial

# Use container-based infrastructure
sudo: false

matrix:
  include:
    - python: '3.7'
      dist: bionic
      sudo: required
    - python: '3.7'
      sudo: required
    - python: '3.6'
      dist: bionic
      sudo: required
    - python: '3.6'
      sudo: required
    - python: '3.6'
      dist: trusty
    - python: '3.5'
      dist: bionic
      sudo: required
    - python: '3.5'
      sudo: required
    - python: '3.5'
      dist: trusty
    - python: '3.4'
      dist: bionic
      sudo: required
    - python: '3.4'
      sudo: required
    - python: '3.4'
      dist: trusty
    - python: '2.7'
      dist: bionic
      sudo: required
    - python: '2.7'
    - python: '2.7'
      dist: trusty
    - python: 'pypy'
    - python: 'pypy'
      dist: trusty
    - python: 'pypy3'
    - python: 'pypy3'
      dist: trusty
    - python: 'nightly'
    - python: 'nightly'
      dist: trusty
    - python: '3.7-dev'
    - python: '3.7-dev'
      dist: trusty
    - python: '3.6-dev'
    - python: '3.6-dev'
      dist: trusty

install:
 - pip install -U tqdm

script:
  - lsb_release -a
  - python ./test.py

