language: python

python:
- 'pypy3'
- 'pypy'
- '3.5'
- '2.7'
- '3.4'
- '3.3'
- '3.2'
- '2.6'

install:
  - sudo apt-get install unrar
  - cp rar unrar /usr/local/bin
  - "pip install pillow"
  - wget http://www.zfight.com/misc/files/textures/envmap_grimmnight.rar
  - unrar x envmap_grimmnight.rar

script:
  - python ./test.py
