language: python

matrix:
  include:
    - python: 3.7
      dist:  xenial
      sudo: required
    - python: 2.7

install:
  - wget https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg
  - wget https://github.com/python-pillow/Pillow/raw/master/Tests/images/hopper.webp
  - wget https://github.com/python-pillow/Pillow/raw/master/Tests/images/hopper.png
  - pip install -U pip
  - pip --version

script:
  - pip install pillow==5.0.0
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'

  - pip install pillow==5.1.0
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'

  - pip install pillow==5.2.0
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'

  - pip install pillow==5.3.0
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'


  - pip install pillow==5.0.0 --no-binary ":all:"
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'

  - pip install pillow==5.1.0 --no-binary ":all:"
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'

  - pip install pillow==5.2.0 --no-binary ":all:"
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'

  - pip install pillow==5.3.0 --no-binary ":all:"
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.webp").load()'
  - python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("hopper.png").load()'
