language: python

dist: xenial

#arch:
#  - amd64  # Default
#  - arm64  # No Python images yet on xenial

python:
  - 'nightly'
  - '3.9-dev'
  - '3.8-dev'
  - '3.7-dev'
  - '3.6-dev'
  - 'pypy'
  - 'pypy3'
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - '2.7'

before_install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py

install:
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py

