language: python

# Would rather default to container-based infrastructure (sudo: false)
# but Xenial requires sudo
sudo: required

# These
matrix:
  include:
    - python: '3.7'
      env: DIST=Xenial
    - python: '3.6'
    - python: '3.6'
      dist: trusty
      sudo: false
    - python: '3.5'
    - python: '3.5'
      dist: trusty
      sudo: false
    - python: '3.4'
      dist: trusty
      sudo: false
    - python: '2.7'
    - python: '2.7'
      dist: trusty
      sudo: false
    - python: 'pypy'
      dist: trusty
      sudo: false
    - python: 'pypy3'
      dist: trusty
      sudo: false
    - python: 'nightly'
    - python: 'nightly'
      dist: trusty
      sudo: false
    - python: '3.7-dev'
    - python: '3.7-dev'
      dist: trusty
      sudo: false
    - python: '3.6-dev'
    - python: '3.6-dev'
      dist: trusty
      sudo: false

install:
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python ./test.py

