language: python

python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'

install:
  - "pip install pillow==2.8.0 django"
  - wget https://cloud.githubusercontent.com/assets/1551551/10288677/a5311cc2-6b57-11e5-8313-a4b8dafb3e00.png -O test-placeholder.png

script:
  - python ./test.py
