language: python

python:
- 'pypy'
- 'pypy2'
- 'pypy3'
- 'pypy5'
- 'pypy-5.3.1'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'

install:
  - "echo $TRAVIS_PYTHON_VERSION"
  - pip install pyyaml

script:
  - python ./test.py
