language: python

python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- 'pypy'

install:
  - pip install coverage

script: coverage run test.py

after_success:
  - coverage report

  # Coverage and quality reports on just the last diff
  - time git fetch origin master:refs/remotes/origin/master
  - time CFLAGS=-O0 pip install --use-wheel diff_cover
  - time coverage xml
  - time diff-cover coverage.xml
  - time diff-quality --violation=pep8
  - time diff-quality --violation=pyflakes
