name: Add PR to project
on:
  pull_request:
    types:
      - ready_for_review

jobs:
  add-to-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/hugovk/projects/1
          github-token: ${{ secrets.YOUR_TOKEN }}
