name: Close stale issues

on:
  schedule:
  - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    if: github.repository_owner == 'hugovk'

    runs-on: ubuntu-latest

    steps:
    - name: "Check issues"
      uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: "Awaiting OP Action"
        close-issue-message: "Closing this issue as no feedback has been received."
        days-before-stale: 1
        days-before-issue-close: 0
        days-before-pr-close: -1
        labels-to-remove-when-unstale: "Awaiting OP Action"
