name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [
          macOS-latest,
        ]
        project: [
          slackclient,
          azure-mgmt-containerregistry,
          azure-graphrbac,
          boto,
          azure-mgmt-authorization,
          ndg-httpsclient,
          django,
          backports-zoneinfo,
          pycryptodome,
          mypy,
          selenium,
          retry,
          statsmodels,
          azureml-dataprep,
          html5lib,
          opt-einsum,
          numba,
          aioitertools,
          pep517,
          retrying,
          azureml-core,
          pkginfo,
          keras,
          lockfile,
          jdcal,
          sanic,
          requests-file,
          h11,
          pysftp,
          pyathena,
          azure-storage-queue,
          llvmlite,
          cachecontrol,
          backports-tempfile,
          backports-weakref,
          kafka-python,
          tensorboard-plugin-wit,
          shapely,
          kubernetes,
          torch,
          pendulum,
          pg8000,
          pycountry,
          pygithub,
          atomicwrites,
          python-http-client,
          inflection,
          thrift,
          stevedore,
          arrow,
          astunparse,
          unidecode,
          humanfriendly,
          jsonpointer,
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install ${{ matrix.project }}

      - name: Test
        run: |
          python --version
