name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        cibw_build:
          - cp36
          - cp310
        cibw_arch:
          - x86_64
          - i686
          - aarch64
        exclude:
          - os: windows-latest
            cibw_arch: aarch64
          - os: macos-latest
            cibw_arch: i686 aarch64

    steps:
      - name: Test
        run: |
           echo ${{ matrix.os }}
           echo ${{ matrix.cibw_build }}
           echo ${{ matrix.cibw_arch }}
