name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [
            pypy-2.7,
            pypy-3.6,
            pypy-3.7,
            pypy-3.6-nightly,
            pypy-3.7-nightly,
            pypy-3.8-nightly,
            pypy-nightly,
        ]
        os: [
          ubuntu-latest,
          macOS-latest,
          windows-latest,
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip

      - name: Test
        run: |
          python --version
