name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [
          ubuntu-20.04,
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U pipdeptree
          python -m pip install -Ur requirements.txt

      - name: pipdeptree 1
        run: |
          pipdeptree

      - name: pipdeptree 2
        run: |
          pipdeptree -p babel --reverse
