name: Test

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "pypy-3.10",
          "pypy-3.9",
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3",
          "3.x",
        ]
        os: [
          windows-latest,
          macOS-latest,
          ubuntu-latest,
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pipx run uv venv --verbose
          pipx run uv pip install --verbose -U pytest
          pipx run uv pip install --verbose -U tqdm

      - name: Test
        run: |
          python --version
          python test.py
          python -m pip --version
          jq --version
