name: Test!

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11-dev", "3.7", "3.8", "3.9", "3.10", "pypy-3.8"]
        os: [
          ubuntu-latest,
          macOS-latest,
          windows-latest,
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: .github/workflows/test.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
          python -m pip install --upgrade tqdm

      - name: Test
        run: |
          python --version --version
