name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [
          ubuntu-latest,
        ]
        project: [
          setuptools,
          six,
          requests,
          python-dateutil,
          idna,
          certifi,
          s3transfer,
          pyyaml,
          pandas,
          packaging,
          pyasn1,
          rsa,
          cffi,
          importlib-metadata,
          pip,
          protobuf,
          click,
          jmespath,
          pyparsing,
          markupsafe,
          zipp,
          jinja2,
          pytz,
          pycparser,
          pyjwt,
          cryptography,
          oauthlib,
          requests-oauthlib,
          colorama,
          cachetools,
          chardet,
          sqlalchemy,
          pyasn1-modules,
          websocket-client,
          docutils,
          decorator,
          werkzeug,
          flask,
          google-cloud-storage,
          toml,
          pyarrow,
          aiohttp,
          isodate,
          docker,
          psutil,
          async-timeout,
          itsdangerous,
          pyrsistent,
          azure-storage-blob,
          msrest,
          tabulate,
          googleapis-common-protos,
          py,
          pygments,
          fsspec,
          matplotlib,
          joblib,
          google-api-python-client,
          azure-common,
          scipy,
          prometheus-client,
          gitpython,
          pluggy,
          gunicorn,
          mypy-extensions,
          mako,
          smmap,
          gitdb,
          sqlparse,
          cloudpickle,
          webencodings,
          asn1crypto,
          uritemplate,
          future,
          cycler,
          defusedxml,
          google-resumable-media,
          tqdm,
          google-auth-httplib2,
          pexpect,
          ipython,
          ptyprocess,
          alembic,
          networkx,
          absl-py,
          scikit-learn,
          prompt-toolkit,
          proto-plus,
          cython,
          ipykernel,
          pyopenssl,
          lxml,
          bleach,
          tornado,
          traitlets,
          entrypoints,
          databricks-cli,
          jedi,
          parso,
          iniconfig,
          backcall,
          pickleshare,
          httplib2,
          beautifulsoup4,
          python-editor,
          nest-asyncio,
          typing-inspect,
          pyzmq,
          nbformat,
          adal,
          ipython-genutils,
          mistune,
          tensorflow-serving-api,
          argcomplete,
          nbconvert,
          jupyter-client,
          prometheus-flask-exporter,
          requests-toolbelt,
          pandocfilters,
          mlflow,
          testpath,
          psycopg2-binary,
          nbclient,
          notebook,
          soupsieve,
          querystring-parser,
          pynacl,
          openpyxl,
          terminado,
          jupyterlab-pygments,
          py4j,
          jupyter-core,
          et-xmlfile,
          ipywidgets,
          backports-entry-points-selectable,
          google-auth-oauthlib,
          matplotlib-inline,
          widgetsnbextension,
          s3fs,
          smart-open,
          debugpy,
          bcrypt,
          configparser,
          aiobotocore,
          jupyterlab-widgets,
          plotly,
          libcst,
          wcwidth,
          imageio,
          google-cloud-bigquery,
          pathspec,
          redis,
          mccabe,
          paramiko,
          lightgbm,
          seaborn,
          ruamel-yaml,
          pywavelets,
          msal,
          pyspark,
          pycodestyle,
          markdown,
          scikit-image,
          portalocker,
          msrestazure,
          msgpack,
          ruamel-yaml-clib,
          azure-identity,
          importlib-resources,
          jeepney,
          gensim,
          secretstorage,
          tensorflow-metadata,
          msal-extensions,
          isort,
          tzlocal,
          pyodbc,
          google-cloud-bigquery-storage,
          pymysql,
          gcsfs,
          google-cloud-logging,
          pycryptodomex,
          tfx-bsl,
          scramp,
          pandas-gbq,
          tensorflow-transform,
          pydata-google-auth,
          threadpoolctl,
          appdirs,
          pbr,
          jupyter-console,
          simplejson,
          tensorflow,
          qtconsole,
          qtpy,
          applicationinsights,
          jupyter,
          cached-property,
          more-itertools,
          termcolor,
          pymongo,
          xmltodict,
          tensorflow-addons,
          tensorflow-data-validation,
          google-cloud-monitoring,
          tensorflow-model-analysis,
          oauth2client,
          pydantic,
          pyflakes,
          setuptools-scm,
          xlrd,
          snowflake-connector-python,
          tensorboard,
          dill,
          oscrypto,
          flake8,
          dataclasses,
          psycopg2,
          zope-interface,
          azure-storage-common,
          tensorflow-estimator,
          pyfarmhash,
          dnspython,
          azure-mgmt-resource,
          datalab,
          lazy-object-proxy,
          h5py,
          keyring,
          nltk,
          sentry-sdk,
          datadog,
          deprecated,
          marshmallow,
          babel,
          mock,
          azure-mgmt-core,
          elasticsearch,
          pytest-runner,
          distro,
          jsonpickle,
          azure-mgmt-storage,
          black,
          xgboost,
          text-unidecode,
          toolz,
          dask,
          azure-mgmt-keyvault,
          asgiref,
          xlsxwriter,
          distributed,
          sortedcontainers,
          azure-nspkg,
          rfc3986,
          docopt,
          google-pasta,
          keras-preprocessing,
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install ${{ matrix.project }}

      - name: Test
        run: |
          python --version
