name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - name: Composer update
        run: |
          sudo composer self-update
