name: Test

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { python-version: "3.12-dev", disable-gil: false }
          - { python-version: "3.12-dev", disable-gil: true }
          - { python-version: "3.13-dev", disable-gil: false }
          - { python-version: "3.13-dev", disable-gil: true }
    name: main
    steps:
      - uses: actions/checkout@v4
      - uses: hugovk/action@test-me-disable-gil
        with:
          python-version: ${{ matrix.python-version }}
          disable-gil: true
      - name: Check version
        run: |
          python --version --version && which python
          python -c "import sysconfig; print(sysconfig.get_config_var('Py_GIL_DISABLED'))"
