name: Test

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13-nogil"]
    name: main
    steps:
      - uses: actions/checkout@v4
      - uses: deadsnakes/action@v3.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - run: python --version --version && which python
