name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy3"]
        os: [
          ubuntu-latest,
          macOS-latest,
          windows-latest,
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install setuptools
          python -m pip install six
          python -m pip install requests
          python -m pip install python-dateutil
          python -m pip install idna
          python -m pip install certifi
          python -m pip install s3transfer
          python -m pip install pyyaml
          python -m pip install pandas
          python -m pip install packaging
          python -m pip install pyasn1
          python -m pip install rsa
          python -m pip install cffi
          python -m pip install importlib-metadata
          python -m pip install pip
          python -m pip install protobuf
          python -m pip install click
          python -m pip install jmespath
          python -m pip install pyparsing
          python -m pip install markupsafe
          python -m pip install zipp
          python -m pip install jinja2
          python -m pip install pytz
          python -m pip install pycparser
          python -m pip install pyjwt
          python -m pip install cryptography
          python -m pip install oauthlib
          python -m pip install requests-oauthlib
          python -m pip install colorama
          python -m pip install cachetools
          python -m pip install chardet
          python -m pip install sqlalchemy
          python -m pip install pyasn1-modules
          python -m pip install websocket-client
          python -m pip install docutils
          python -m pip install decorator
          python -m pip install werkzeug
          python -m pip install flask
          python -m pip install google-cloud-storage
          python -m pip install toml
          python -m pip install pyarrow
          python -m pip install aiohttp
          python -m pip install isodate
          python -m pip install docker
          python -m pip install psutil
          python -m pip install async-timeout
          python -m pip install itsdangerous
          python -m pip install pyrsistent
          python -m pip install azure-storage-blob
          python -m pip install msrest
          python -m pip install tabulate
          python -m pip install googleapis-common-protos
          python -m pip install py
          python -m pip install pygments
          python -m pip install fsspec
          python -m pip install matplotlib
          python -m pip install joblib
          python -m pip install google-api-python-client
          python -m pip install azure-common
          python -m pip install scipy
          python -m pip install prometheus-client
          python -m pip install gitpython
          python -m pip install pluggy
          python -m pip install gunicorn
          python -m pip install mypy-extensions
          python -m pip install mako
          python -m pip install smmap
          python -m pip install gitdb
          python -m pip install sqlparse
          python -m pip install cloudpickle
          python -m pip install webencodings
          python -m pip install asn1crypto
          python -m pip install uritemplate
          python -m pip install future
          python -m pip install cycler
          python -m pip install defusedxml
          python -m pip install google-resumable-media
          python -m pip install tqdm
          python -m pip install google-auth-httplib2
          python -m pip install pexpect
          python -m pip install ipython
          python -m pip install ptyprocess
          python -m pip install alembic
          python -m pip install networkx
          python -m pip install absl-py
          python -m pip install scikit-learn
          python -m pip install prompt-toolkit
          python -m pip install proto-plus
          python -m pip install cython
          python -m pip install ipykernel
          python -m pip install pyopenssl
          python -m pip install lxml
          python -m pip install bleach
          python -m pip install tornado
          python -m pip install traitlets
          python -m pip install entrypoints
          python -m pip install databricks-cli
          python -m pip install jedi
          python -m pip install parso
          python -m pip install iniconfig
          python -m pip install backcall
          python -m pip install pickleshare
          python -m pip install httplib2
          python -m pip install beautifulsoup4
          python -m pip install python-editor
          python -m pip install nest-asyncio
          python -m pip install typing-inspect
          python -m pip install pyzmq
          python -m pip install nbformat
          python -m pip install adal
          python -m pip install ipython-genutils
          python -m pip install mistune
          python -m pip install tensorflow-serving-api
          python -m pip install argcomplete
          python -m pip install nbconvert
          python -m pip install jupyter-client
          python -m pip install prometheus-flask-exporter
          python -m pip install requests-toolbelt
          python -m pip install pandocfilters
          python -m pip install mlflow
          python -m pip install testpath
          python -m pip install psycopg2-binary
          python -m pip install nbclient
          python -m pip install notebook
          python -m pip install soupsieve
          python -m pip install querystring-parser
          python -m pip install pynacl
          python -m pip install openpyxl
          python -m pip install terminado
          python -m pip install jupyterlab-pygments
          python -m pip install py4j
          python -m pip install jupyter-core
          python -m pip install et-xmlfile
          python -m pip install ipywidgets
          python -m pip install backports-entry-points-selectable
          python -m pip install google-auth-oauthlib
          python -m pip install matplotlib-inline
          python -m pip install widgetsnbextension
          python -m pip install s3fs
          python -m pip install smart-open
          python -m pip install debugpy
          python -m pip install bcrypt
          python -m pip install configparser
          python -m pip install aiobotocore
          python -m pip install jupyterlab-widgets
          python -m pip install plotly
          python -m pip install libcst
          python -m pip install wcwidth
          python -m pip install imageio
          python -m pip install google-cloud-bigquery
          python -m pip install pathspec
          python -m pip install redis
          python -m pip install mccabe
          python -m pip install paramiko
          python -m pip install lightgbm
          python -m pip install seaborn
          python -m pip install ruamel-yaml
          python -m pip install pywavelets
          python -m pip install msal
          python -m pip install pyspark
          python -m pip install pycodestyle
          python -m pip install markdown
          python -m pip install scikit-image
          python -m pip install portalocker
          python -m pip install msrestazure
          python -m pip install msgpack
          python -m pip install ruamel-yaml-clib
          python -m pip install azure-identity
          python -m pip install importlib-resources
          python -m pip install jeepney
          python -m pip install gensim
          python -m pip install secretstorage
          python -m pip install tensorflow-metadata
          python -m pip install msal-extensions
          python -m pip install isort
          python -m pip install tzlocal
          python -m pip install pyodbc
          python -m pip install google-cloud-bigquery-storage
          python -m pip install pymysql
          python -m pip install gcsfs
          python -m pip install google-cloud-logging
          python -m pip install pycryptodomex
          python -m pip install tfx-bsl
          python -m pip install scramp
          python -m pip install pandas-gbq
          python -m pip install tensorflow-transform
          python -m pip install pydata-google-auth
          python -m pip install threadpoolctl
          python -m pip install appdirs
          python -m pip install pbr
          python -m pip install jupyter-console
          python -m pip install simplejson
          python -m pip install tensorflow
          python -m pip install qtconsole
          python -m pip install qtpy
          python -m pip install applicationinsights
          python -m pip install jupyter
          python -m pip install cached-property
          python -m pip install more-itertools
          python -m pip install termcolor
          python -m pip install pymongo
          python -m pip install xmltodict
          python -m pip install tensorflow-addons
          python -m pip install tensorflow-data-validation
          python -m pip install google-cloud-monitoring
          python -m pip install tensorflow-model-analysis
          python -m pip install oauth2client
          python -m pip install pydantic
          python -m pip install pyflakes
          python -m pip install setuptools-scm
          python -m pip install xlrd
          python -m pip install snowflake-connector-python
          python -m pip install tensorboard
          python -m pip install dill
          python -m pip install oscrypto
          python -m pip install flake8
          python -m pip install dataclasses
          python -m pip install psycopg2
          python -m pip install zope-interface
          python -m pip install azure-storage-common
          python -m pip install tensorflow-estimator
          python -m pip install pyfarmhash
          python -m pip install dnspython
          python -m pip install azure-mgmt-resource
          python -m pip install datalab
          python -m pip install lazy-object-proxy
          python -m pip install h5py
          python -m pip install keyring
          python -m pip install nltk
          python -m pip install sentry-sdk
          python -m pip install datadog
          python -m pip install deprecated
          python -m pip install marshmallow
          python -m pip install babel
          python -m pip install mock
          python -m pip install azure-mgmt-core
          python -m pip install elasticsearch
          python -m pip install pytest-runner
          python -m pip install distro
          python -m pip install jsonpickle
          python -m pip install azure-mgmt-storage
          python -m pip install black
          python -m pip install xgboost
          python -m pip install text-unidecode
          python -m pip install toolz
          python -m pip install dask
          python -m pip install azure-mgmt-keyvault
          python -m pip install asgiref
          python -m pip install xlsxwriter
          python -m pip install distributed
          python -m pip install sortedcontainers
          python -m pip install azure-nspkg
          python -m pip install rfc3986
          python -m pip install docopt
          python -m pip install google-pasta
          python -m pip install keras-preprocessing
          python -m pip install slackclient
          python -m pip install boto
          python -m pip install azure-mgmt-containerregistry
          python -m pip install azure-graphrbac
          python -m pip install azure-mgmt-authorization
          python -m pip install django
          python -m pip install mypy
          python -m pip install ndg-httpsclient
          python -m pip install pycryptodome
          python -m pip install backports-zoneinfo
          python -m pip install selenium
          python -m pip install retry
          python -m pip install statsmodels
          python -m pip install html5lib
          python -m pip install opt-einsum
          python -m pip install numba
          python -m pip install aioitertools
          python -m pip install pep517
          python -m pip install retrying
          python -m pip install pkginfo
          python -m pip install azureml-dataprep
          python -m pip install azureml-core
          python -m pip install lockfile
          python -m pip install keras
          python -m pip install jdcal
          python -m pip install h11
          python -m pip install requests-file
          python -m pip install sanic
          python -m pip install pysftp
          python -m pip install pyathena
          python -m pip install azure-storage-queue
          python -m pip install cachecontrol
          python -m pip install llvmlite
          python -m pip install kafka-python
          python -m pip install kubernetes
          python -m pip install shapely
          python -m pip install backports-tempfile
          python -m pip install tensorboard-plugin-wit
          python -m pip install backports-weakref
          python -m pip install pendulum
          python -m pip install torch
          python -m pip install atomicwrites
          python -m pip install pg8000
          python -m pip install pygithub
          python -m pip install inflection
          python -m pip install pycountry
          python -m pip install python-http-client
          python -m pip install thrift
          python -m pip install stevedore
          python -m pip install arrow
          python -m pip install unidecode
          python -m pip install astunparse
          python -m pip install snowballstemmer
          python -m pip install blinker

      - name: Test
        run: |
          python --version
